import type { DicEntry, Freq } from './types';

/* Dicionário: reconhece descrições de nota fiscal e itens de dieta.
   Copiado de feira-app.html:330-411, com dois ajustes da fase 2:
   `pp` virou `pp2` — é a quantidade mensal pra uma casa de 2 pessoas, e o nome
   antigo sugeria por pessoa (ver sugQty);
   `loss` entra só onde o rendimento real difere dos 25% padrão do cfg. Arroz e
   feijão até ganham peso ao cozinhar, mas têm cook:0 e não entram na conta. */
export const DIC: DicEntry[] = [
 {k:['sobrecoxa'],n:'Sobrecoxa desossada',c:'Proteínas',f:'mes',u:'kg',cook:1,pp2:2},
 {k:['file peito','peito fgo','peito de frango','file de frango','frango','coxa de frango'],n:'Filé de frango',c:'Proteínas',f:'mes',u:'kg',cook:1,pp2:2},
 {k:['coxao','patinho','alcatra','musculo','contra file','picanha','bov '],n:'Carne bovina (coxão/patinho)',c:'Proteínas',f:'mes',u:'kg',cook:1,pp2:1.5},
 {k:['lombo suino','suina','suino','copa lombo','pernil'],n:'Carne suína',c:'Proteínas',f:'mes',u:'kg',cook:1,pp2:0.5},
 {k:['tilapia','pescada','salmao','merluza','peixe'],n:'Peixe (tilápia)',c:'Proteínas',f:'mes',u:'kg',cook:1,pp2:1,loss:18},
 {k:['atum','sardinha'],n:'Atum em lata',c:'Proteínas',f:'mes',u:'lata',cook:0,pp2:3},
 {k:['ovo'],n:'Ovos',c:'Proteínas',f:'quinzena',u:'bandeja',cook:0,pp2:4.5},
 {k:['hamburguer'],n:'Carne moída / hambúrguer',c:'Proteínas',f:'mes',u:'kg',cook:1,pp2:0.5,loss:30},
 {k:['whey','proteina isolada'],n:'Whey protein',c:'Proteínas',f:'mes',u:'pote',cook:0,pp2:0.5},
 {k:['pense','yopro','iog grego','iogurte grego','danone','iogurte proteico'],n:'Iogurte proteico',c:'Laticínios',f:'quinzena',u:'un',cook:0,pp2:8},
 {k:['iog natural','iogurte natural','iog '],n:'Iogurte natural',c:'Laticínios',f:'quinzena',u:'un',cook:0,pp2:10},
 {k:['requeijao'],n:'Requeijão',c:'Laticínios',f:'quinzena',u:'pote',cook:0,pp2:0.75},
 {k:['ricota','cottage'],n:'Ricota / cottage',c:'Laticínios',f:'quinzena',u:'pote',cook:0,pp2:0.5},
 {k:['coalho'],n:'Queijo coalho',c:'Laticínios',f:'quinzena',u:'kg',cook:0,pp2:0.45},
 {k:['mucarela','mussarela','muçarela','prato','minas'],n:'Queijo (muçarela/prato)',c:'Laticínios',f:'quinzena',u:'kg',cook:0,pp2:0.25},
 {k:['parmesao'],n:'Queijo parmesão',c:'Laticínios',f:'mes',u:'un',cook:0,pp2:0.5},
 {k:['leite'],n:'Leite',c:'Laticínios',f:'quinzena',u:'L',cook:0,pp2:1.5},
 {k:['manteiga','margarina'],n:'Manteiga',c:'Laticínios',f:'mes',u:'pote',cook:0,pp2:0.5},
 {k:['arroz'],n:'Arroz',c:'Grãos e massas',f:'mes',u:'kg',cook:0,pp2:2.5},
 {k:['feijao'],n:'Feijão',c:'Grãos e massas',f:'mes',u:'kg',cook:0,pp2:1.5},
 {k:['macarrao','massa g','linguine','fusilli','farfalle','penne','espaguete','massa '],n:'Massa',c:'Grãos e massas',f:'mes',u:'pacote',cook:0,pp2:2.5},
 {k:['flocao','cuscuz','milho nao transg','fuba'],n:'Flocão / cuscuz',c:'Grãos e massas',f:'mes',u:'pacote',cook:0,pp2:2},
 {k:['aveia'],n:'Aveia',c:'Grãos e massas',f:'mes',u:'un',cook:0,pp2:0.5},
 {k:['granola'],n:'Granola',c:'Grãos e massas',f:'mes',u:'un',cook:0,pp2:0.5},
 {k:['grao de bico','lentilha','quinoa'],n:'Grão de bico / lentilha',c:'Grãos e massas',f:'mes',u:'un',cook:0,pp2:0.5},
 {k:['tapioca','goma'],n:'Tapioca / goma',c:'Grãos e massas',f:'quinzena',u:'kg',cook:0,pp2:0.25},
 {k:['farinha'],n:'Farinha',c:'Grãos e massas',f:'mes',u:'kg',cook:0,pp2:0.5},
 {k:['pao frances','pao fab','pao careca'],n:'Pão francês',c:'Pães',f:'semana',u:'kg',cook:0,pp2:0.25},
 {k:['pao form','pao de forma','pao integral'],n:'Pão de forma',c:'Pães',f:'quinzena',u:'pacote',cook:0,pp2:1},
 {k:['tortilha','rap10','rap 10','pao folha','wrap'],n:'Tortilha / rap',c:'Pães',f:'quinzena',u:'pacote',cook:0,pp2:1},
 {k:['torrada','biscoito de arroz'],n:'Torrada',c:'Pães',f:'quinzena',u:'pacote',cook:0,pp2:1},
 {k:['banana'],n:'Banana',c:'Frutas',f:'semana',u:'kg',cook:0,pp2:1.2},
 {k:['uva'],n:'Uva',c:'Frutas',f:'semana',u:'un',cook:0,pp2:0.5},
 {k:['tangerina','poncã','ponca','mexerica','laranja'],n:'Tangerina / laranja',c:'Frutas',f:'semana',u:'kg',cook:0,pp2:0.5},
 {k:['morango'],n:'Morango',c:'Frutas',f:'semana',u:'caixa',cook:0,pp2:0.5},
 {k:['abacaxi'],n:'Abacaxi',c:'Frutas',f:'semana',u:'un',cook:0,pp2:0.5},
 {k:['maca','maçã'],n:'Maçã',c:'Frutas',f:'semana',u:'kg',cook:0,pp2:0.5},
 {k:['manga'],n:'Manga',c:'Frutas',f:'semana',u:'kg',cook:0,pp2:0.5},
 {k:['abacate'],n:'Abacate',c:'Frutas',f:'semana',u:'kg',cook:0,pp2:0.4},
 {k:['melao','melancia','kiwi','mamao','goiaba'],n:'Fruta da estação',c:'Frutas',f:'semana',u:'kg',cook:0,pp2:0.5},
 {k:['alface','rucula','folha','couve','espinafre'],n:'Folhas (alface etc.)',c:'Verduras e legumes',f:'semana',u:'maço',cook:0,pp2:1},
 {k:['tomate'],n:'Tomate',c:'Verduras e legumes',f:'semana',u:'kg',cook:0,pp2:0.5},
 {k:['cenoura'],n:'Cenoura',c:'Verduras e legumes',f:'semana',u:'kg',cook:0,pp2:0.3},
 {k:['beterraba'],n:'Beterraba',c:'Verduras e legumes',f:'semana',u:'kg',cook:0,pp2:0.3},
 {k:['brocolis','brócolis','couve flor'],n:'Brócolis',c:'Verduras e legumes',f:'semana',u:'maço',cook:0,pp2:0.5},
 {k:['batata inglesa','batata lisa','batata doce','inhame','macaxeira'],n:'Batata / raízes',c:'Verduras e legumes',f:'quinzena',u:'kg',cook:0,pp2:0.75},
 {k:['pepino'],n:'Pepino',c:'Verduras e legumes',f:'semana',u:'kg',cook:0,pp2:0.2},
 {k:['pimentao'],n:'Pimentão',c:'Verduras e legumes',f:'semana',u:'kg',cook:0,pp2:0.2},
 {k:['cebola'],n:'Cebola',c:'Verduras e legumes',f:'quinzena',u:'kg',cook:0,pp2:0.5},
 {k:['cebolinha','coentro','salsinha','tempero verde','manjericao'],n:'Temperos frescos',c:'Verduras e legumes',f:'semana',u:'un',cook:0,pp2:1},
 {k:['abobora','jerimum','chuchu','berinjela','abobrinha'],n:'Legumes variados',c:'Verduras e legumes',f:'semana',u:'kg',cook:0,pp2:0.5},
 {k:['cafe'],n:'Café',c:'Despensa',f:'mes',u:'un',cook:0,pp2:1},
 {k:['acucar','açúcar','adocante'],n:'Açúcar / adoçante',c:'Despensa',f:'mes',u:'kg',cook:0,pp2:0.5},
 {k:['azeite'],n:'Azeite',c:'Despensa',f:'mes',u:'un',cook:0,pp2:0.5},
 {k:['oleo'],n:'Óleo',c:'Despensa',f:'mes',u:'un',cook:0,pp2:1},
 {k:['vinagre'],n:'Vinagre',c:'Despensa',f:'mes',u:'un',cook:0,pp2:0.5},
 {k:['sal ','tempero','colorau','alho','oregano'],n:'Temperos secos',c:'Despensa',f:'mes',u:'mês',cook:0,pp2:0.5},
 {k:['barra prot','barra de proteina','crisp bar'],n:'Barra de proteína',c:'Despensa',f:'quinzena',u:'un',cook:0,pp2:4},
 {k:['snickers','twix','batom','chocolate','framboesa','doce de leite','goiabada','sorvete','bala'],n:'Doces',c:'Extras',f:'mes',u:'un',cook:0,pp2:1,extra:1},
 {k:['isotonico','refrigerante','suco','cerveja','vinho','energetico'],n:'Bebidas',c:'Extras',f:'mes',u:'un',cook:0,pp2:2,extra:1},
 {k:['batata palito','congelado','pizza','lasanha','nuggets'],n:'Congelados prontos',c:'Extras',f:'mes',u:'un',cook:0,pp2:0.5,extra:1},
 {k:['salgadinho','pipoca','biscoito rech'],n:'Snacks',c:'Extras',f:'mes',u:'un',cook:0,pp2:1,extra:1},
 {k:['deterg','limpol'],n:'Detergente',c:'Limpeza',f:'mes',u:'un',cook:0,pp2:2.5,grp:'limpeza'},
 {k:['lava roupa','coquel','sabao','omo','ariel','tixan'],n:'Sabão de roupa',c:'Limpeza',f:'mes',u:'un',cook:0,pp2:0.5,grp:'limpeza'},
 {k:['amaciant','comfort','downy'],n:'Amaciante',c:'Limpeza',f:'mes',u:'un',cook:0,pp2:0.5,grp:'limpeza'},
 {k:['esponja','pano','flanela','rodo','vassoura'],n:'Esponja / pano',c:'Limpeza',f:'mes',u:'un',cook:0,pp2:0.5,grp:'limpeza'},
 {k:['desinfet','pinho','multiuso','veja','limpa vidro'],n:'Desinfetante / multiuso',c:'Limpeza',f:'mes',u:'un',cook:0,pp2:1,grp:'limpeza'},
 {k:['agua sanitaria','candida','cloro','alvejante'],n:'Água sanitária',c:'Limpeza',f:'mes',u:'un',cook:0,pp2:1,grp:'limpeza'},
 {k:['saco de lixo','saco lixo'],n:'Saco de lixo',c:'Limpeza',f:'mes',u:'rolo',cook:0,pp2:1,grp:'limpeza'},
 {k:['bom ar','aromatiz','odorizador'],n:'Aromatizador',c:'Limpeza',f:'mes',u:'un',cook:0,pp2:0.5,grp:'limpeza'},
 {k:['sacola','papel toalha','guardanapo','filme pvc','papel aluminio'],n:'Descartáveis',c:'Limpeza',f:'mes',u:'un',cook:0,pp2:1,grp:'limpeza'},
 {k:['papel higien'],n:'Papel higiênico',c:'Higiene',f:'mes',u:'fardo',cook:0,pp2:0.5,grp:'higiene'},
 {k:['shampoo','condicionador'],n:'Shampoo / condicionador',c:'Higiene',f:'mes',u:'un',cook:0,pp2:1,grp:'higiene'},
 {k:['sabonete','sabão de coco'],n:'Sabonete',c:'Higiene',f:'mes',u:'un',cook:0,pp2:3,grp:'higiene'},
 {k:['creme dental','pasta de dente','colgate','sorriso','fio dental','enxaguante'],n:'Higiene bucal',c:'Higiene',f:'mes',u:'un',cook:0,pp2:1.5,grp:'higiene'},
 {k:['desodorante','rexona','nivea'],n:'Desodorante',c:'Higiene',f:'mes',u:'un',cook:0,pp2:1,grp:'higiene'},
 {k:['absorvente','intimus','coletor'],n:'Absorvente',c:'Higiene',f:'mes',u:'pacote',cook:0,pp2:1,grp:'higiene'},
 {k:['lamina','gillette','barbear'],n:'Lâmina de barbear',c:'Higiene',f:'mes',u:'un',cook:0,pp2:0.5,grp:'higiene'},
 {k:['hidratante','protetor solar','creme corporal'],n:'Hidratante',c:'Higiene',f:'mes',u:'un',cook:0,pp2:0.5,grp:'higiene'},
 {k:['racao','areia higienica','petisco'],n:'Pets',c:'Outros',f:'mes',u:'un',cook:0,pp2:1},
];

/* `s` é a etiqueta curta que cabe na linha da lista, onde a frequência deixou
   de ser seção e virou detalhe do item. */
export const FREQ: Record<Freq, { t: string; h: string; s: string }> = {mes:{t:'1x por mês',h:'compra grande',s:'mês'},
            quinzena:{t:'a cada 15 dias',h:'reposição',s:'15d'},
            semana:{t:'toda semana',h:'frutas, verduras e fresco',s:'sem'}};

export const CATORDER: string[] = ['Proteínas','Laticínios','Grãos e massas','Pães','Frutas','Verduras e legumes','Despensa','Extras','Limpeza','Higiene','Outros'];

export const MESES: string[] = ['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'];
