import type { Item, PriceBase } from './types';
import { nid } from './format';

/* Template de exemplo: casal com dieta prescrita, preços Natal/RN 2026.
   Copiado sem alteração de feira-app.html:422-511. */
export const EX_BASE: PriceBase = {
 'Filé de frango':{price:25.49,unit:'kg',n:4},'Sobrecoxa desossada':{price:20.24,unit:'kg',n:1},
 'Carne bovina (coxão/patinho)':{price:52.16,unit:'kg',n:5},'Carne suína':{price:29.74,unit:'kg',n:2},
 'Ovos':{price:9.29,unit:'bandeja',n:3},'Iogurte proteico':{price:14.79,unit:'un',n:2},
 'Iogurte natural':{price:3.88,unit:'un',n:20},'Requeijão':{price:20.99,unit:'pote',n:2},
 'Queijo coalho':{price:42.49,unit:'kg',n:2},'Queijo parmesão':{price:32.48,unit:'un',n:1},
 'Leite':{price:7.99,unit:'L',n:6},'Manteiga':{price:31.99,unit:'pote',n:1},
 'Arroz':{price:5.29,unit:'kg',n:5},'Feijão':{price:8.34,unit:'kg',n:3},'Massa':{price:9.99,unit:'pacote',n:4},
 'Flocão / cuscuz':{price:5.69,unit:'pacote',n:4},'Aveia':{price:12.99,unit:'un',n:1},
 'Granola':{price:54.99,unit:'un',n:1},'Pão francês':{price:15.99,unit:'kg',n:1},
 'Pão de forma':{price:11.49,unit:'pacote',n:2},'Tortilha / rap':{price:9.49,unit:'pacote',n:2},
 'Banana':{price:6.99,unit:'kg',n:1},'Uva':{price:14.99,unit:'un',n:1},'Tangerina / laranja':{price:15.99,unit:'kg',n:1},
 'Folhas (alface etc.)':{price:4.99,unit:'maço',n:1},'Tomate':{price:6.99,unit:'kg',n:1},
 'Batata / raízes':{price:13.99,unit:'kg',n:1},'Cebola':{price:7.49,unit:'kg',n:1},
 'Temperos frescos':{price:3.99,unit:'un',n:1},'Café':{price:30.99,unit:'un',n:2},
 'Açúcar / adoçante':{price:6.39,unit:'kg',n:1},'Azeite':{price:58.48,unit:'un',n:1},
 'Barra de proteína':{price:13.64,unit:'un',n:2},'Detergente':{price:2.58,unit:'un',n:6},
 'Sabão de roupa':{price:59.98,unit:'un',n:1},'Amaciante':{price:40.98,unit:'un',n:2},
 'Esponja / pano':{price:27.99,unit:'un',n:1},
};

/** [nome, cat, freq, qtd, unid, preço, cozinha, ativo, nota] */
type ExRow = [string, string, string, number, string, number, number, number, string];

export const EX_RAW: ExRow[] = [
 ['Filé de frango','Proteínas','mes',4,'kg',25.49,1,1,''],
 ['Sobrecoxa desossada','Proteínas','mes',4,'kg',20.24,1,1,'melhor custo por kg'],
 ['Carne bovina (coxão/patinho)','Proteínas','mes',3.2,'kg',52.16,1,1,''],
 ['Carne suína','Proteínas','mes',0.9,'kg',29.74,1,1,''],
 ['Peixe (tilápia)','Proteínas','mes',1.5,'kg',30,1,1,'preço estimado'],
 ['Atum em lata','Proteínas','mes',6,'lata',8,0,1,'preço estimado'],
 ['Ovos','Proteínas','quinzena',15,'bandeja',9.29,0,1,'~5 ovos/dia'],
 ['Iogurte proteico','Laticínios','quinzena',4,'garrafa',15.28,0,1,'garrafa grande rende mais que o pote'],
 ['Iogurte natural','Laticínios','quinzena',30,'un',3.88,0,1,'lanche diário'],
 ['Requeijão','Laticínios','quinzena',2,'pote',20.99,0,1,''],
 ['Queijo coalho','Laticínios','quinzena',1.4,'kg',42.49,0,1,''],
 ['Queijo (muçarela/prato)','Laticínios','quinzena',0.4,'kg',45,0,1,''],
 ['Ricota / cottage','Laticínios','quinzena',1,'pote',18,0,0,'substituição do requeijão'],
 ['Queijo parmesão','Laticínios','mes',1,'un',32.48,0,0,''],
 ['Leite','Laticínios','quinzena',6,'L',7.99,0,1,''],
 ['Manteiga','Laticínios','mes',1,'pote',31.99,0,1,''],
 ['Arroz','Grãos e massas','mes',4,'kg',5.29,0,1,''],
 ['Feijão','Grãos e massas','mes',3,'kg',8.34,0,1,''],
 ['Massa','Grãos e massas','mes',3,'pacote',9.99,0,1,''],
 ['Flocão / cuscuz','Grãos e massas','mes',6,'pacote',5.69,0,1,''],
 ['Aveia','Grãos e massas','mes',3,'un',12.99,0,1,''],
 ['Granola','Grãos e massas','mes',1,'un',54.99,0,1,'versão comum sai ~1/3 do preço'],
 ['Tapioca / goma','Grãos e massas','quinzena',0.5,'kg',12,0,1,''],
 ['Pão francês','Pães','semana',2,'kg',15.99,0,1,'comprar fresco 2x na semana'],
 ['Pão de forma','Pães','quinzena',2,'pacote',11.49,0,1,'congela bem'],
 ['Tortilha / rap','Pães','quinzena',2,'pacote',9.49,0,1,''],
 ['Banana','Frutas','semana',5,'kg',6.99,0,1,''],
 ['Uva','Frutas','semana',2,'un',14.99,0,1,'pacote 500g'],
 ['Tangerina / laranja','Frutas','semana',2,'kg',15.99,0,1,''],
 ['Morango','Frutas','semana',4,'caixa',9,0,1,'preço estimado'],
 ['Abacaxi','Frutas','semana',3,'un',6,0,1,'preço estimado'],
 ['Maçã','Frutas','semana',2,'kg',10,0,1,'preço estimado'],
 ['Folhas (alface etc.)','Verduras e legumes','semana',6,'maço',4.99,0,1,''],
 ['Tomate','Verduras e legumes','semana',5,'kg',6.99,0,1,''],
 ['Cenoura','Verduras e legumes','semana',1.5,'kg',7,0,1,'preço estimado'],
 ['Beterraba','Verduras e legumes','semana',1,'kg',6,0,1,'preço estimado'],
 ['Brócolis','Verduras e legumes','semana',4,'maço',8,0,1,'preço estimado'],
 ['Batata / raízes','Verduras e legumes','quinzena',3,'kg',13.99,0,1,''],
 ['Cebola','Verduras e legumes','quinzena',2,'kg',7.49,0,1,''],
 ['Temperos frescos','Verduras e legumes','semana',4,'un',3.99,0,1,''],
 ['Café','Despensa','mes',2,'un',30.99,0,1,'gourmet; tradicional é bem mais barato'],
 ['Açúcar / adoçante','Despensa','mes',1,'kg',6.39,0,1,''],
 ['Azeite','Despensa','mes',1,'un',58.48,0,1,'premium; há boas opções pela metade'],
 ['Óleo','Despensa','mes',2,'un',9,0,1,'preço estimado'],
 ['Vinagre','Despensa','mes',1,'un',4.58,0,1,''],
 ['Temperos secos','Despensa','mes',1,'mês',20,0,1,'preço estimado'],
 ['Barra de proteína','Despensa','quinzena',4,'un',13.64,0,1,''],
 ['Chocolate 70%','Despensa','mes',2,'barra',12,0,1,'porção diária controlada'],
 ['Doces','Extras','mes',3,'un',30,0,0,''],
 ['Bebidas','Extras','mes',6,'un',13.99,0,0,''],
 ['Congelados prontos','Extras','mes',1,'un',38.98,0,0,''],
 ['Detergente','Limpeza','mes',6,'un',2.58,0,1,''],
 ['Sabão de roupa','Limpeza','mes',1,'un',59.98,0,1,''],
 ['Amaciante','Limpeza','mes',1,'un',40.98,0,1,''],
 ['Esponja / pano','Limpeza','mes',1,'un',27.99,0,1,''],
 ['Desinfetante / multiuso','Limpeza','mes',2,'un',10,0,1,'preço estimado'],
 ['Água sanitária','Limpeza','mes',2,'un',6,0,1,'preço estimado'],
 ['Saco de lixo','Limpeza','mes',2,'rolo',10,0,1,'preço estimado'],
 ['Descartáveis','Limpeza','mes',2,'un',8,0,1,'preço estimado'],
 ['Papel higiênico','Higiene','mes',1,'fardo',30,0,1,'preço estimado'],
 ['Shampoo / condicionador','Higiene','mes',2,'un',18,0,1,'preço estimado'],
 ['Sabonete','Higiene','mes',6,'un',3,0,1,'preço estimado'],
 ['Higiene bucal','Higiene','mes',2,'un',6,0,1,'preço estimado'],
 ['Desodorante','Higiene','mes',2,'un',14,0,1,'preço estimado'],
 ['Absorvente','Higiene','mes',2,'pacote',10,0,1,'preço estimado'],
 ['Lâmina de barbear','Higiene','mes',1,'un',15,0,1,'preço estimado'],
 ['Hidratante','Higiene','mes',1,'un',20,0,1,'preço estimado'],
];

export function exampleItems(): Item[] {
  return EX_RAW.map((r) => ({
    id: nid(),
    name: r[0],
    cat: r[1],
    freq: r[2] as Item['freq'],
    qty: r[3],
    unit: r[4],
    price: r[5],
    cook: !!r[6],
    on: !!r[7],
    nota: r[8] || '',
  }));
}
